pipeline {
    agent any

    stages {
        stage('Run Docker Container') {
            steps {
                sh '''
                    docker rm -f keycloak || true
                    docker rm -f keycloak_postgres || true
                    docker compose -f TheraPose_v1.0/docker-compose.yml up -d --build
                '''
            }
        }
    }
}