pipeline {
    agent any

    stages {
        stage('Deploy Keycloak with Docker Compose') {
            steps {
                script {
                    // Stop and remove existing containers
                    sh '''
                        docker-compose -f TheraPose_v1.0/docker-compose.yml down || true
                    '''

                    // Start updated containers (with --build if images need rebuild)
                    sh '''
                        docker-compose -f TheraPose_v1.0/docker-compose.yml up -d --build
                    '''
                }
            }
        }
    }
}