services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build: .
    image: bryanhert/keycloak-yoga:26.1.3
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # your FastAPI Dockerfile
    container_name: fastapi
    command: uvicorn proyecto.src.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - keycloak
      - postgres

volumes:
  postgres_data: