services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build: .
    image: bryanhert/keycloak-yoga:26.1.3
    container_name: keycloak
    user: root
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_LOG_LEVEL=DEBUG
      - KC_SMTP_HOST=smtp.gmail.com
      - KC_SMTP_PORT=465
      - KC_SMTP_SSL=true
      - KC_SMTP_STARTTLS=false
      - KC_SMTP_FROM=83espajuge@gmail.com
      - KC_SMTP_USER=83espajuge@gmail.com
      - KC_SMTP_PASSWORD=jbrvibgtdxnddeyr

    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/opt/keycloak/keycloak-entrypoint.sh"]
    volumes:
      - ./keycloak-entrypoint.sh:/opt/keycloak/keycloak-entrypoint.sh

volumes:
  postgres_data: